# Generated by Django 3.1.2 on 2021-02-01 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('is_trusted', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pools', models.IntegerField()),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo_main', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.realtor')),
            ],
        ),
    ]
