# Generated by Django 3.1.6 on 2021-03-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20210306_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_date',
            new_name='timestamp',
        ),
    ]
