# Generated by Django 3.1.6 on 2021-03-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20210306_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='join_date',
            new_name='timestamp',
        ),
    ]
