# Generated by Django 3.1.6 on 2021-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20210306_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtor',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
