# Generated by Django 3.1.1 on 2020-09-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, choices=[('TS', 'Trade Shows'), ('W', 'Workshops'), ('I', 'Internet Streams'), ('WE', 'Webinars'), ('S', 'Seminars'), ('C', 'Conferences'), ('G', 'Galas'), ('P', 'Parties'), ('U', 'Uncategorized'), ('R', 'Reunions')], max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
