# Generated by Django 3.1.2 on 2021-02-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='summary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
