# Generated by Django 3.1.6 on 2021-02-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210214_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(default='jude', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventcity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventstate'),
        ),
    ]
