# Generated by Django 3.1.6 on 2021-02-26 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20210224_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 12, 3, 6, 407957, tzinfo=utc)),
        ),
    ]
