# Generated by Django 3.1.6 on 2021-02-26 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210226_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 13, 38, 11, 248708, tzinfo=utc)),
        ),
    ]
