# Generated by Django 3.1.6 on 2021-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210302_1811'),
        ('payment', '0013_auto_20210302_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='core.Event'),
        ),
    ]
