# Generated by Django 3.1.6 on 2021-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20210302_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='user_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
