# Generated by Django 3.1.6 on 2021-03-06 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0016_userorder_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='CreatorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_sold', models.IntegerField()),
                ('tickets_remaining', models.IntegerField()),
                ('tickets_paid_for', models.IntegerField()),
                ('tickets_total', models.IntegerField()),
                ('payment_id', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
