# Generated by Django 3.1.6 on 2021-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20210317_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='ticket_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='ticket_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
