# Generated by Django 3.1.6 on 2021-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_userorder_is_ticket_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation',
            name='order_reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='signal_object',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
