# Generated by Django 3.1.6 on 2021-03-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_auto_20210302_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportationcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='transportation',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transportation.operator'),
        ),
    ]
