# Generated by Django 3.1.6 on 2021-03-06 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transportation', '0005_auto_20210304_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='email',
        ),
        migrations.AlterField(
            model_name='operator',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transportation.transportationcategory'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='list_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='photo_main',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='transportationcategory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
