# Generated by Django 3.1.6 on 2021-04-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_auto_20210306_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='operator',
            new_name='creator',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
