# Generated by Django 3.1.6 on 2021-04-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_auto_20210417_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportationcategory',
            options={'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='category',
            new_name='vehicle_type',
        ),
    ]
