# Generated by Django 3.1.6 on 2021-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0009_auto_20210417_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
