# Generated by Django 3.1.6 on 2021-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_transportation_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
